### ISSUE TITLE
Crash on suspend

### ISSUE THREAD

**Issue by linuzzz** [Taiko2k/Tauon#1260] opened 2024-11-07 17:22 UTC
Hello,

I'm on Fedora 41 with Gnome and also if I checked the option "block suspend" on settings Tauon (installed as flatpak) allow the system to suspend and it crashes when the system goes suspending. Starting the player on the command line I get this error:

`/app/bin/com.github.taiko2k.tauonmb.sh: line 14:     3 Segmentation fault      (core dumped) python3 /app/bin/tauon.py "$@"
`

I wonder if this could be a flatpak permission...?

Thanks!

**Comment by C0rn3j** [comment] 2024-11-14 23:11
Providing backtrace from the coredump would probably be useful.

https://docs.flatpak.org/en/latest/debugging.html

**Comment by C0rn3j** [comment] 2024-12-29 22:20
Closing as dupe of #1084

**Closed by C0rn3j** 2024-12-29 22:20 UTC
Labels: unconfirmed bug
