### ISSUE TITLE
flatpak won't start

### ISSUE THREAD

**Issue by dln949** [Taiko2k/Tauon#658] opened 2022-01-17 08:10 UTC
running on Ubuntu Bionic.  

issuing  flatpak run com.github.taiko2k.tauonmb  produces this:  No previous window state

And all I see is a boundary of an otherwise 100% transparent window.

**Comment by Taiko2k** [comment] 2022-01-17 09:03
Try run `flatpak update`

**Comment by dln949** [comment] 2022-01-17 15:23
Nothing changed, still the same problem.

**Comment by Taiko2k** [comment] 2022-01-17 22:34
Try run a system update (including graphics drivers), then try `flatpak update` again. This issue is usually cause by mismatched graphics driver versions, in which doing an update usually fixes. If it doesn't then I'm not sure what's wrong.

**Comment by dln949** [comment] 2022-01-17 23:28
I did that but that did not help.

**Comment by Merulox** [comment] 2022-01-18 23:38
ArcoLinux & KDE Plasma here, having the same issue with the AUR package

**Comment by C0rn3j** [comment] 2024-12-02 23:27
@dln949 @Merulox can either of you reproduce it with the current 7.8.3 Flatpak?

If so, can you reproduce it on regular 7.8.3, and if so, can you also reproduce it on git master?

There's at least this issue - https://github.com/Taiko2k/Tauon/issues/1034 - but that seems to be limited to Wayland setups forcing Tauon to use Xwayland.

**Comment by dln949** [comment] 2024-12-03 01:15
Running 7.8.3 flatpak on ubuntu bionic (wayland) starts just fine now for me.  

(But [https://github.com/Taiko2k/Tauon/issues/1222](url) is still a problem.)

**Comment by C0rn3j** [comment] 2024-12-03 08:06
Try git master for that and let me know there, both Taiko and me committed possible fixes for it since 7.8.3.

**Closed by C0rn3j** 2024-12-03 08:06 UTC
