### ISSUE TITLE
Wrong artist image for some artists

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/Tauon#607] opened 2021-11-10 15:12 UTC
Well the title pretty much explains all, when using the artist list some images is wrong and if i hover the mouse on them tauon says no artist image has been found, despite last fm and musicbrainz being on (and logged in), how to solve this?

And by the way, most of the artist images are just an album cover, is this right?

**Comment by Taiko2k** [comment] 2021-11-11 22:41
Unfortunately this feature kind of died when lastfm pulled their service. The best way now to get images is to enter a discogs key into Tauon

**Comment by legacychimera247** [comment] 2021-11-12 12:22
ok, i'll look into that, already having a discogs account...

**Comment by legacychimera247** [comment] 2021-11-12 12:58
set that but it does not change the issue...

**Comment by Taiko2k** [comment] 2021-11-12 20:35
Do you have the auto download artist info setting enabled?

**Comment by legacychimera247** [comment] 2021-11-13 13:37
the autofetch artist data function is enabled, if that's the thing, but maybe it's just using cover arts and not artist images and i was just wrong...

**Comment by Taiko2k** [comment] 2021-11-13 14:13
It uses the cover art as a fallback if it doesn't have an artist image

**Comment by legacychimera247** [comment] 2021-11-13 22:42
yes but i'm having only artist images, even for artists like u2 and oasis...

**Comment by Taiko2k** [comment] 2021-11-13 22:44
Maybe try menu > database > clear image cache

**Comment by legacychimera247** [comment] 2021-11-15 08:34
Already done that, it's working only for covers...

**Comment by C0rn3j** [comment] 2024-12-29 22:29
Are you still able to reproduce the issue in the latest [development build](https://github.com/Taiko2k/Tauon/wiki/Development-builds)?

**Comment by Taiko2k** [comment] 2024-12-29 23:56
Lastfm scraping was re-implemented since this issue was opened so I assume this original issue as is is no longer applicable.

**Comment by legacychimera247** [comment] 2024-12-31 00:25
unfortunately i don't remember which artist was, i need to better check, but i suppose the feature is working now

**Comment by C0rn3j** [comment] 2024-12-31 17:31
Closing then, if you can still find something wrong with it do open a new issue please.

**Closed by C0rn3j** 2024-12-31 17:31 UTC
Labels: unconfirmed bug
