### ISSUE TITLE
Sidebar glitching

### ISSUE THREAD

**Issue by demeralde** [Taiko2k/Tauon#591] opened 2021-10-20 22:24 UTC
The sidebar keeps clipping:

![Screenshot from 2021-10-20 23-11-29](https://user-images.githubusercontent.com/9282837/138180836-a7b7e08a-6458-46a4-bde8-996fd7ba4d4b.png)

## Environment

* Tauon 6.8.0
* Pop!_OS 21.04
* GNOME 3.38.5

**Comment by Taiko2k** [comment] 2021-10-21 04:19
Oh, yeah that's just a small layout quirk, it wouldn't be related to performance issues.

**Comment by dspacejs** [comment] 2021-10-21 04:33
@Taiko2k just confirmed the GUI glitches for my OS occur without Tauon open. So it's probably not related to this

**Comment by C0rn3j** [comment] 2024-12-05 13:45
Closing this, since it was 3 years ago and seems to have been an issue with your OS as it didn't affect just Tauon.

Let me know if this actually still happens today on current versions in which case we can reopen it again.

**Closed by C0rn3j** 2024-12-05 13:45 UTC
Labels: Low Priority
