### ISSUE TITLE
Can't import lossless .aiff files

### ISSUE THREAD

**Issue by Benjamin-Connelly** [Taiko2k/Tauon#1161] opened 2024-05-30 16:07 UTC
Windows v7.7.2  client.

Not able to import .aiff files.

**Comment by C0rn3j** [comment] 2024-11-14 23:27
7.8.3 Linux loads https://filesamples.com/samples/audio/aiff/sample1.aiff just fine, do you still have the issue on the current version?

If so, can you launch Tauon through Powershell (if that's possible, which should hopefully provide the logs) and see if anything gets logged?

**Comment by Taiko2k** [comment] 2024-11-14 23:36
This was fixed in version 7.8.1, the issue is the last successful Windows build release was 7.8.0.

**Closed** 2024-12-21 19:08 UTC
